Feature/create
masakichi-eng/NekoPro-Tsubuyaki pull request #12
Opened 2021-07-19 14:05 UTC by RYOTA-EAST

# Why
画像を説明文付きで共有

# What
記事を投稿

## 備考
rubocopで以下の様になったので
app/models/user.rb:2:3: C: Rails/HasManyOrHasOneDependent: Specify a :dependent option.
  has_many :posts
  ^^^^^^^^
dependent: :destroyをつけ、userが削除された際にpostも削除をいうオプションを付け
通りました、確認お願いします

2021-07-19 14:24 UTC, minty1202 requested changes
基本に忠実な綺麗な書き方だと思いました。
良かったです。

2021-07-19 14:24 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +class Users::PostsController < ApplicationController
class Users::PostsController < UserController
にしていただけると助かります

2021-07-19 14:24 UTC, minty1202 commented on app/models/post.rb
> +  validates :photo, presence: true
どちらでもいいですが、紹介までに
```
with_option presence: true do

end
```
という書き方もできます

2021-07-19 14:24 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +  describe "GET /index" do
テストの記述もできればお願いします
requestとmodel
余力があったらでいいです

2021-07-19 14:24 UTC, minty1202 commented on app/views/users/posts/new.html.slim
> +  = render 'layouts/error_messages', model: form.object
エラーはlayoutに書いた方が綺麗かと思います。
表記が崩れるようであればこのままでも大丈夫です

2021-07-19 14:24 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +      redirect_to root_path
せっかくなのでnoticeもつけてみてください
投稿できませした。的なもの

2021-07-19 15:10 UTC, RYOTA-EAST commented on app/controllers/users/posts_controller.rb
> +class Users::PostsController < ApplicationController
そのまま入力で修正を加えると
投稿画面に遷移する際に以下のエラー画面になります
[エラー画面](https://gyazo.com/8f81106ee92f23612490ae2af0acd5db)

継承先を変更しているんだろうという理解度で、対処法が思いつかないという状況です。
指導お願いします。

2021-07-19 15:21 UTC, RYOTA-EAST commented on app/views/users/posts/new.html.slim
> +  = render 'layouts/error_messages', model: form.object
layoutに書くというのはどういう感じでしょうか？
検索してみましたが、上記のように部分テンプレートから読み出す以外の方法が見つけられなかったです

2021-07-20 02:36 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +class Users::PostsController < ApplicationController
すみません、私の綴り間違えです。
user_controllerの1行目ApplicationControllerに書き直してください。本当にすみません

2021-07-20 02:37 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +      redirect_to root_path
できました。ですね。すみません

2021-07-20 02:50 UTC, minty1202 commented on app/views/users/posts/new.html.slim
> +  = render 'layouts/error_messages', model: form.object
viewファイルというのは各ページlayoutというページをベースにして表示されています。
共通で表示する内容（headerやfooter等）はviewファイルごとに書くのではなく、layoutファイルに記述します。
エラー内容は内容は違えど、どのページでも表示をしますので、layoutファイルに書いた方が共通化ができ楽です
viewsディレクトリのlayoutsにapplication.html.slimがあるかと思います。別ファイルでlayoutを作ってもいいですが、今回はapplication.html.slimの = yieldの上に
render 'error_messages', model: form.object
を記述するとすっきりするかと。という意味ですね。

2021-07-20 02:55 UTC, minty1202 commented on app/views/layouts/_error_messages.html.slim
> +- if model.errors.any?
気づいてしまった。
app/views/users/posts/new.html.slimの
render 'layouts/error_messages', model: form.objectをlayoutに移す場合は
sharedというディレクトリを作成して、そこに移動してください
render 'layouts/error_messages', model: form.objectを移動せず、app/views/users/posts/new.html.slimでそのまま使う場合は
postsディレクトリに移動をお願いします

2021-07-20 03:05 UTC, minty1202 commented on app/views/layouts/_error_messages.html.slim
> +- if model.errors.any?
蛇足かもしれませんが、
ディレクトリを移すとrenderの呼び出す書き方も微妙に異なりますので、お願いします

2021-07-24 14:05 UTC, RYOTA-EAST commented on app/views/layouts/_error_messages.html.slim
> +- if model.errors.any?
postsディレクトリの方で実行しました

2021-07-24 14:15 UTC, RYOTA-EAST commented
主な修正点は
- テスト記述
- ビュー作成

ビューの見た目は[こちら](https://gyazo.com/1b47a24622efe9a2551b2443547641bb)です
file_fieldのボタンの見た目をfigmaの様にするのができなかったです。

2021-07-25 13:01 UTC, minty1202 requested changes
前回よりもよくなってます😊
ありがとうございます

2021-07-25 13:01 UTC, minty1202 commented on app/views/users/posts/new.html.slim
> +        path[d="M21 41.8334C17.8501 41.8422 14.74 41.1295 11.9083 39.75C10.872 39.2459 9.87902 38.6571 8.93958 37.9895L8.65417 37.7812C6.07046 35.8742 3.95807 33.4004 2.47917 30.55C0.94945 27.5997 0.
これは一体？

2021-07-25 13:01 UTC, minty1202 commented on spec/models/post_spec.rb
> +        @post.description = '123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/'
140字ということを表現されたい？
```
@post.description = 's' * 140
```
とかはいかがでしょうか？

2021-07-25 13:01 UTC, minty1202 commented on spec/models/post_spec.rb
> +        @post.description = '123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/a'
同上

2021-07-25 13:01 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +RSpec.describe "Users::Posts", type: :request do
```
RSpec.describe Users::PostsController, type: :request do
```

2021-07-25 13:01 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response.status).to eq 302
302よりも redirect_to ....
の方がテストとしては正確かも。

2021-07-25 13:01 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response).to redirect_to root_path
~上のと同じでは？？~

2021-07-25 13:01 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response.status).to eq 302
あーそういうことか、
成功することだけを検証したいのであれば
```
expect(response.status).to be_successful
```
とかにする方がいいかと

2021-07-25 13:01 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response.body).to include "Description can&#39;t be blank"
これ成功するのでしょうか？
```
Description can not be blank
```
とかな気がします。

2021-07-25 13:01 UTC, minty1202 commented on app/views/layouts/application.html.slim
> +    = stylesheet_link_tag "post", media: "all"
多分いらない。なくても反応するはずです。

2021-07-25 13:01 UTC, minty1202 commented on app/views/layouts/application.html.slim
> +    = stylesheet_link_tag "post", media: "all"
もし反応しないようであれば、そのままでも大丈夫です。
取り込んだあと私が修正します

2021-07-25 13:01 UTC, minty1202 commented on app/views/general/index.html.slim
> +  = content_tag(:div, value, class: key)
これって何の表記でしょうか？
エラー？？

2021-07-25 13:34 UTC, RYOTA-EAST commented on spec/models/post_spec.rb
> +        @post.description = '123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/'
絶対その方がいいです

2021-07-25 13:45 UTC, RYOTA-EAST commented on app/views/users/posts/new.html.slim
> +        path[d="M21 41.8334C17.8501 41.8422 14.74 41.1295 11.9083 39.75C10.872 39.2459 9.87902 38.6571 8.93958 37.9895L8.65417 37.7812C6.07046 35.8742 3.95807 33.4004 2.47917 30.55C0.94945 27.5997 0.
user名、横の人型アイコンを出すのに必要だと思って入れてます
figmaの人型を右クリックsvgをコピーして貼り付けで表示できていて
こんな感じです。

2021-07-25 13:57 UTC, RYOTA-EAST commented on spec/requests/users/posts_spec.rb
> +        expect(response.body).to include "Description can&#39;t be blank"
`Description can not be blank`
では成功しませんでした。
エラーの中でresponse.bodyと思われる内容を表示してくれるのですが
その中でDescription can&#39;t be blankとなっており
成功しています。HTML特殊文字コードという様です
[参考サイト](http://www.shurey.com/js/labo/character.html)

2021-07-25 14:04 UTC, RYOTA-EAST commented on app/views/layouts/application.html.slim
> +    = stylesheet_link_tag "post", media: "all"
消すと反応しなくなるのでそのままでいきます

2021-07-25 14:08 UTC, RYOTA-EAST commented on app/views/general/index.html.slim
> +  = content_tag(:div, value, class: key)
「投稿完了しました」のメッセージ表示です。
現在投稿完了後にindexにリダイレクトする様にしていてそこに記述しました。
思ったのはapplication.html.slimの先頭の方がいいですかね？

2021-07-25 14:17 UTC, RYOTA-EAST commented on spec/requests/users/posts_spec.rb
> +        expect(response.status).to eq 302
statusが付いていると期待する値が302となるので
`expect(response).to be_successful`
として実行すると以下のgyazoのようなエラーが発生します
[gyazo](https://gyazo.com/5983d8999c1294fc29d9897c37df479d)

2021-07-25 15:54 UTC, minty1202 commented on app/views/users/posts/new.html.slim
> +        path[d="M21 41.8334C17.8501 41.8422 14.74 41.1295 11.9083 39.75C10.872 39.2459 9.87902 38.6571 8.93958 37.9895L8.65417 37.7812C6.07046 35.8742 3.95807 33.4004 2.47917 30.55C0.94945 27.5997 0.
であれば、fontawesomeで行っていただけると助かります

2021-07-25 15:59 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response.body).to include "Description can&#39;t be blank"
特殊文字コードは知ってますが、
あまり使いたくはないですね。
まぁいっか。

2021-07-25 16:00 UTC, minty1202 commented on app/views/layouts/application.html.slim
> +    = stylesheet_link_tag "post", media: "all"
多分アセッツの設定方法が違うから反応しないのだと思いますが、マージ後私の方で修正します

2021-07-25 16:01 UTC, minty1202 commented on app/views/general/index.html.slim
> +  = content_tag(:div, value, class: key)
そうですね、書くのであればアプリケーションの方がいいかと思います

2021-07-25 16:05 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +        expect(response.status).to eq 302
be_truthy または be_successful で通らないのであれば、正常な処理をされていないことが予想されます。
どうしても通せないようであれば私の方で修正します

2021-07-25 16:10 UTC, minty1202 commented on app/views/users/posts/new.html.slim
> +        path[d="M21 41.8334C17.8501 41.8422 14.74 41.1295 11.9083 39.75C10.872 39.2459 9.87902 38.6571 8.93958 37.9895L8.65417 37.7812C6.07046 35.8742 3.95807 33.4004 2.47917 30.55C0.94945 27.5997 0.
人型を使いたいということであれば、アイコン関係になるため
fontawesomeを使った方がいいですね。
導入が無理そうであれば、私の方で入れます。

2021-07-25 16:13 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +RSpec.describe "Users::Posts", type: :request do
この書き方にして欲しかったのですが、伝わらなかったですかね😅
すみません

2021-07-25 16:15 UTC, minty1202 commented
コンフリクト解消後フツーのレビューに変えていただいて大丈夫です。
修正しきれないところは私の方で行います

2021-07-26 12:30 UTC, RYOTA-EAST commented on spec/requests/users/posts_spec.rb
> +RSpec.describe "Users::Posts", type: :request do
すいません、それは修正しましたが
まだ他の内容が解決していないのでプッシュしてません。
対応済みでこの内容は問題ありませんでした。

2021-07-26 12:40 UTC, RYOTA-EAST commented on spec/requests/users/posts_spec.rb
> +        expect(response.status).to eq 302
be_truthyで通りました

2021-07-27 14:29 UTC, RYOTA-EAST commented on app/views/users/posts/new.html.slim
> +        path[d="M21 41.8334C17.8501 41.8422 14.74 41.1295 11.9083 39.75C10.872 39.2459 9.87902 38.6571 8.93958 37.9895L8.65417 37.7812C6.07046 35.8742 3.95807 33.4004 2.47917 30.55C0.94945 27.5997 0.
fontawesomeを実装しました
方法は

- Gemを入れる
- [yarn addでインストールする](https://qiita.com/SaitoJP/items/bda11d7bd4e8ad35331a)

等あるようですが、今回はapplication.html.slimにscriptを追記で実行しました
推奨の方法があるのでしょうか？それとも動作すれば手段どれでもいいのでしょうか？

2021-07-27 14:52 UTC, minty1202 approved these changes
![image](https://user-images.githubusercontent.com/62473570/127176229-e18d3b9f-46b0-43e7-896d-2cc0c678f3fa.png)
お疲れ様です😊
基本的なところは問題なさそうなのでマージしてしまいます。

細かいところは私の方で修正しますね

2021-07-27 14:52 UTC, merged