Feature/devise
masakichi-eng/NekoPro-Tsubuyaki pull request #16
Opened 2021-07-24 09:49 UTC by programmingnuoh

# why
devise導入途中経過を一旦ご確認いただくため

# what
devise導入〜ビューファイル作成（とりあえずerbのままです）

進捗遅れ気味で申し訳ございません。ご確認のほどお願いします。

2021-07-24 12:58 UTC, minty1202 requested changes
基本的にゆっくりで大丈夫です。
進捗に関してはオンラインですのでご安心ください😊
どこかが遅れてもサポートできるようにしてますので、他のことは考えなくて大丈夫ですよ。
気にさせてしまってすみません。

変更をしていただきたいのは~2点~1点です。
~nameをnicknameにしてください。~
devaiseの応用的な使い方をして欲しかったので可能であればcontrollerを拡張していただけると。難しければ大丈夫です。

もし拡張しない場合だとしてもおそらく今のままだとlast_name等追加したカラムはものは保存できていないのではないでしょうか？

また手順通りにuserのマイグレートを書き換えていただいてありがとうございます。

2021-07-24 12:58 UTC, minty1202 commented on config/routes.rb
> +  devise_for :users
コントローラを拡張して欲しかったんですが、記事の内容わかりずらかったですかね😅
```
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
```
とかって形になるはずです。

2021-07-24 12:58 UTC, minty1202 commented on db/migrate/20210714140127_devise_create_users.rb
> +      t.string :name, null:false
nicknameにしてもらえると
```
docker-compose run --rm web rails db:rollback # これを2回 または
docker-compose run --rm web rails db:migrate:down VERSION=20210714140127
```
でmigrate statusをdownにできるはずですので、恐れ入りますが編集をお願いします

2021-07-24 13:00 UTC, minty1202 commented
マージは私がするので、とりあえずドラフトのままで大丈夫ですー

2021-08-04 14:03 UTC, programmingnuoh commented on db/migrate/20210714140127_devise_create_users.rb
> +      t.string :name, null:false
name→nickname変更しました！
ご確認お願いします。

2021-08-04 14:10 UTC, minty1202 commented on app/models/user.rb
> +    validates :name
nicknameに合わせてもらえると

2021-08-04 14:11 UTC, programmingnuoh commented on config/routes.rb
> +  devise_for :users
すみません、記事を見失ってしまったのですがどちらに書かれていましたでしょうか
これは手書きで書いて良いものなのでしょうか

2021-08-04 14:13 UTC, minty1202 commented on config/routes.rb
> +  devise_for :users
https://qiita.com/Yama-to/items/54ab4ce08e126ef7dade
こちらです😊
手書きで大丈夫ですよ

2021-08-04 14:16 UTC, programmingnuoh commented on app/models/user.rb
> +    validates :name
こちらも変更完了いたしました！
ご確認お願いします

2021-08-07 08:01 UTC, programmingnuoh commented on config/routes.rb
> +  devise_for :users
遅くなりました💦
ルーティング変更したのでご確認お願いいたします。

2021-08-07 11:29 UTC, minty1202 requested changes

2021-08-07 11:29 UTC, minty1202 commented on app/models/user.rb
> +  validates :name, presence: true
あれ？戻ってます？？

2021-08-07 11:29 UTC, minty1202 commented on app/models/profile.rb
> +class Profile < ApplicationRecord
Profileは別のブランチで指示しようとおもっていたのにありがとうございます。😊
とりあえず、このまま一旦放置でも大丈夫ですよ

2021-08-11 14:41 UTC, programmingnuoh commented
@minty1202 
CUIでuser登録できたので一度ご確認お願いします！！

2021-08-13 12:01 UTC, minty1202 reviewed
確認いたしました。
どうしましょうか、一度マージされますか？
マージされる場合は一度develop-neko1を取り込んでいただけると
このまま作り続けていただいても大丈夫です

2021-09-12 09:51 UTC, programmingnuoh commented
# why
ユーザー登録機能についてご確認いただくため

# what
user登録・profile登録の実装
コンフリクトが発生しているところは、Feature/deviseの情報を削除する形で大丈夫でしょうか？
（こっちの情報の方が古いと思ったので…）

# view
https://gyazo.com/3a1c9a972d275632c9d55bbea742ffca
https://gyazo.com/499999bd49ae062f754a64bef342052e

ご確認お願いします。

2021-09-13 10:49 UTC, minty1202 requested changes

2021-09-13 10:49 UTC, minty1202 commented on Gemfile
> +gem 'jquery-rails'
yarnで入れいているはずですので
gem で入れる必要はないはずです。
最新のdevelopを取り込んでください

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/confirmations_controller.rb
> +# frozen_string_literal: true
このファイルは必要ないです

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/omniauth_callbacks_controller.rb
> +# frozen_string_literal: true
同じく

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/passwords_controller.rb
> +# frozen_string_literal: true
同じく

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +    @user = User.new
この記述はなくても動くはずです

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +    render :new_profile
この動作でuserが作られるとは思えないです。
profileが入っていることでややこしくなっているのだと思うのですが、
今回はprofileは考えなくていいです。
nickname email passwordのみで考えてください

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +    sign_in(:user, @user)
同じく
profileの作成はされなくていいので
せっかく作っていただいてますが、消していただけると

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  end
profile情報は大丈夫です

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/unlocks_controller.rb
> +# frozen_string_literal: true
このファイルは消していただいて大丈夫です

2021-09-13 10:49 UTC, minty1202 commented on app/javascript/packs/application.js
> +require("bootstrap")
yarnで管理しているので
最新のブランチを取り込んでください

2021-09-13 10:49 UTC, minty1202 commented on app/models/profile.rb
> +class Profile < ApplicationRecord
ややこしくなるので、申し訳ないですが一旦消していただけると。（ ;  ; ）

2021-09-13 10:49 UTC, minty1202 commented on app/models/user.rb
> +  has_one :profile
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
不要ファイルですので消していただけると

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p>Welcome <%= @email %>!</p>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/mailer/email_changed.html.erb
> +<p>Hello <%= @email %>!</p>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/mailer/password_change.html.erb
> +<p>Hello <%= @resource.email %>!</p>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p>Hello <%= @resource.email %>!</p>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/mailer/unlock_instructions.html.erb
> +<p>Hello <%= @resource.email %>!</p>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/passwords/edit.html.erb
> +<h2>Change your password</h2>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/passwords/new.html.erb
> +<h2>Forgot your password?</h2>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/registrations/create_profile.html.slim
> += stylesheet_link_tag "users", media: "all"
ここも不要なはず

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/registrations/new.html.slim
> += stylesheet_link_tag "users", media: "all"
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/registrations/new_profile.html.slim
> += stylesheet_link_tag "users", media: "all"
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/registrations/create_profile.html.slim
> += stylesheet_link_tag "users", media: "all"
記事の手順通りに行えば
app/views/users/registrations
ディレクトリにできるはずです

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/sessions/new.html.slim
> += stylesheet_link_tag "users", media: "all"
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/shared/_error_messages.html.slim
> +- if resource.errors.any?
ここも不要です

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
同上

2021-09-13 10:49 UTC, minty1202 commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
同上

2021-09-13 10:49 UTC, minty1202 commented on db/migrate/20210714140303_create_profiles.rb
> +  def change
せっかく作っていただいて申し訳ないですが、消していただけると

2021-09-13 10:49 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +    render :new_profile
また、userの作成には必ずsuperを通すようにしてください

2021-09-13 10:49 UTC, minty1202 commented on spec/models/profile_spec.rb
> +require 'rails_helper'
せっかく書いていただいて忍びないですが、消していただけると。

2021-09-13 10:49 UTC, minty1202 commented on spec/models/user_spec.rb
> +        @user.nickname = ""
からでも登録できるのはおかしいので必須にしてください

2021-09-13 10:49 UTC, minty1202 commented on spec/models/user_spec.rb
> +        expect(@user.errors.full_messages).to include("Email can't be blank")
言語を日本語にしていて英語の文章がくるのは疑問ですが、
ブラウザ上は日本語が出てくるのでしょうか？

2021-09-13 10:49 UTC, minty1202 commented on spec/rails_helper.rb
> +I18n.locale = "en"
日本語にするのであれば
ja
ただ、全てのテストが英語ですのでこのままでいいです

2021-09-13 13:14 UTC, programmingnuoh commented on spec/models/user_spec.rb
> +        expect(@user.errors.full_messages).to include("Email can't be blank")
ブラウザ上では日本語を、テストは英語を表示するよう設定しました！
https://gyazo.com/e46a1980d5ec98f077dc3020dea4be87

2021-09-16 02:50 UTC, minty1202 requested changes
意図するコードになかなか誘導できてなくてすみません。
だいぶ良くなりました

2021-09-16 02:50 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  # end
ここのコメントアウトを外して
```ruby
def create
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  super
end
```

としてください

2021-09-16 02:50 UTC, minty1202 commented on app/controllers/application_controller.rb
> +    end
拡張したuserの方で記述するのでここは消してください

2021-09-16 02:50 UTC, minty1202 commented on config/routes.rb
> +  end
profileを無くしたので、消しておいていただけると

2021-09-16 02:50 UTC, minty1202 commented on spec/models/user_spec.rb
> +        @user.nickname = ""
it 'nicknameがないと登録できない' do

2021-09-16 02:50 UTC, minty1202 commented on spec/models/user_spec.rb
> +        expect(@user.errors.full_messages).to include("Email can't be blank")
ありがとうございます

2021-09-16 02:50 UTC, minty1202 commented on Gemfile
> +
不要

2021-09-16 02:56 UTC, minty1202 commented
> # why
> ユーザー登録機能についてご確認いただくため
> 
> # what
> user登録・profile登録の実装
> コンフリクトが発生しているところは、Feature/deviseの情報を削除する形で大丈夫でしょうか？
> （こっちの情報の方が古いと思ったので…）
> 
> # view
> https://gyazo.com/3a1c9a972d275632c9d55bbea742ffca
> https://gyazo.com/499999bd49ae062f754a64bef342052e
> 
> ご確認お願いします。

こちらのコメント見逃していました。
東さんと一緒に行った方がいいところもあるかと思いますので、一旦レビュワーに東さんも追加しています

2021-09-16 14:04 UTC, programmingnuoh commented on app/controllers/users/registrations_controller.rb
> +  # end
上記について、application_controller.rbに記述しないのに何か理由があるのでしょうか？（可読性の向上とか…）
よかったらご教授いただけると嬉しいです！

2021-09-17 01:02 UTC, minty1202 commented on app/controllers/users/registrations_controller.rb
> +  # end
まず、deviseを使った場合のカラムを追加する場合どういった方法があるかから説明します。
1. コントローラーに直接記述する（拡張している場合のみ可能 私がお願いした方
2. アプリケーションコントローラに記述（スクールで習うやり方 いでさんが元々されていた方
3. gemに対して制約を外すよう書き換える（モンキーパッチと呼ばれるやり方

3はほぼやりませんが、1、2のやり方が多いです。
ではスクールではなぜ2のやり方をやるのかというと、コントローラの拡張はハードルが高いと言う点とスクールのようにuserしか認証しないようなアプリしか作らないからです。
その場合はコントローラーを拡張せずアプリケーションから無理やり変更するようにしたほうが記述が少なく済みます。

では今回なぜこのようにお願いしたかと言いますと、可読性もありますが、一番は
userのみしか認証しないアプリケーションはほぼ存在しないからと、今後サービスを大きくした際に対応できる手法を学んで欲しいからです。
例えば現場でアプリを作る際は最低でもuserとadminに相当するものが作られます。
一般ユーザーと管理者ですね。
そうなるとお互いに使うカラムは変わってくると思います。
アプリケーションコントローラーで書く書き方ですとそこで書いたものが全てに適用されるため、柔軟な対応ができなくなります。
今回adminを作ったとしてadminにはnicknameは不要だとするとアプリケーションに記述した場合adminには不要なnicknameを許容すると言うことになりバグになりやすくセキュリティ的にも避けた方がいいです。


今回はuserしか取り扱わないのでアプリケーションでも構わないですが、こう言った書き方に触れて欲しいと言う意図もとこちらに記述をお願いしました。


と言う感じでお答えになっているでしょうか？😅

2021-09-17 02:36 UTC, RYOTA-EAST commented on Gemfile
> -gem 'devise'
`gem 'devise'`
は入っていないなと動作しないのではないでしょうか？

2021-09-17 03:19 UTC, RYOTA-EAST commented on app/controllers/users/registrations_controller.rb
> +    devise_parameter_santizer.permit(:sign_up, keys: [:nickname])
sanitizerの「n」の後の「i」が抜けてます

2021-09-17 03:55 UTC, RYOTA-EAST commented on app/views/devise/registrations/new.html.slim
> +  main.form-signin
新規登録のみフッター位置が画面サイズに変化対応できていません
app/views/devise/sessions/new.html.slimと比べて
bootstrapを適応するclass指定をbodyでなくmainの方に切り替えると直ると思います

2021-09-17 04:04 UTC, RYOTA-EAST commented on Gemfile
> +
@minty1202 
ここで不要なのってgem 'pry-rails'のみですよね？

2021-09-17 05:02 UTC, RYOTA-EAST commented
@minty1202 
動作確認をしたところ、コメントに書いたところが直れば
記事投稿からいいね機能まで動作します

@programmingnuoh 
気になる点をコメントさせていただきました。
もう一点変更点がないところへのコメント方法がわからずこちらに書きますが

- app/views/shared/_header_nav.html.slimに
「ログイン」、「ログアウト」、「新規登録」のボタンがあるといいと思います
動作確認する際にも楽だと思うので

よろしくお願いします

2021-09-17 05:35 UTC, minty1202 commented on Gemfile
> +
私のミスです。
gem 'pry-rails'
のみです。失礼いたしました

2021-09-17 05:36 UTC, minty1202 commented on Gemfile
> -gem 'devise'
私のミスです。申し訳ありません。
ありがとうございます

2021-09-18 07:53 UTC, programmingnuoh commented on app/controllers/users/registrations_controller.rb
> +  # end
ありがとうございます！
検索してみても2のやり方が一番出てくるので個人と現場のやり方で違うのかな？と思い質問させていただきました
勉強になりました🙇‍♀️

2021-09-18 09:02 UTC, RYOTA-EAST commented
@programmingnuoh 
お疲れ様です、修正後の動作確認して問題ないと思います。
コンフリクトが発生しているので解消お願いします。

2021-09-19 11:06 UTC, minty1202 approved these changes

2021-09-19 11:06 UTC, minty1202 commented on app/assets/stylesheets/bootstrap.css
> +@charset "UTF-8";
このファイルは恐らく不要かと。
消しても問題無く動くようであれば消していただけると、
見た目上不具合があるようであればそのままで大丈夫です

2021-09-19 11:06 UTC, minty1202 commented on app/javascript/packs/bootstrap.js
> +  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
同上

2021-09-20 06:08 UTC, merged