Feature/delete
masakichi-eng/NekoPro-Tsubuyaki pull request #20
Opened 2021-08-07 03:51 UTC by RYOTA-EAST

# Why
完全に消去するのでなく、
復元・確認できるようにデータを残したまま無効にする
# What
投稿の論理削除

# View
[gyazoリンク](https://gyazo.com/33618793c0985589edb4e9ecd53109b1)の通りで
### 変更点

- 編集の横に削除ボタンが追加
- ボタン左にmargin設定

です

2021-08-07 08:29 UTC, minty1202 requested changes
色々と調べていただいているみたいでありがとうございます

2021-08-07 08:29 UTC, minty1202 commented on Gemfile
> +gem 'discard'
せっかくなんで
```
gem 'discard', '~> 1.2'
```
にしましょうか

2021-08-07 08:29 UTC, minty1202 commented on app/models/post.rb
> +
おそらくこれだけですと、userが削除された場合、理論削除されないかと思います

```
class Comment < ActiveRecord::Base
  belongs_to :post

  include Discard::Model
  scope :kept, -> { undiscarded.joins(:post).merge(Post.kept) }

  def kept?
    undiscarded? && post.kept?
  end
end
```
こういった記述が必要になるかと
[https://github.com/jhawthorn/discard](url)

2021-08-07 08:29 UTC, minty1202 commented on db/migrate/20210806153632_add_discarded_at_to_posts.rb
> +    add_index :posts, :discarded_at
```
add_column :posts, :discarded_at, :datetime, comment: 'hoge'
```

2021-08-07 08:29 UTC, minty1202 commented on db/schema.rb
> +    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
なぜ、deviseの記述？？？

2021-08-07 08:29 UTC, minty1202 commented on db/schema.rb
> +    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
現状develop-neko1にはdeviseは入っていないです。修正してもらえると

2021-08-07 08:29 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +
モデルのテストに
- 論理削除できること
- 復元できることと、
- userを削除した場合に論理削除できていること

この三つを可能であれば足していただけると

2021-08-07 12:39 UTC, RYOTA-EAST commented on db/schema.rb
> +    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
実際の作成に入る前に別ブランチでdevise入れて試した際の
userのデータベースが残っていて
[修正前userデータ](https://gyazo.com/dcdf3e86aceee6ec3e1dff002abf91d4)

データベースを
`rails db:migrate:reset`
でリセットすることでdb/schema.rbとローカルuserテーブルもdeviseがない状態に修正できたと思います
[修正後userデータ](https://gyazo.com/35e05a6201e11187cf81048ccb68be7a)

gem 'devise'を入れていないので不思議だったのですが
discardでカラムを追加する時に実行したmigrateで
データベースからdb/schema.rbに反映してしまった？という感じでしょうか？

2021-08-07 12:46 UTC, minty1202 commented on db/schema.rb
> +    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
原因分かりかねますが、前のブランチのデータベースの状態を
新しいブランチでmigrateをしたことで反映してしまったとかでしょう

2021-08-08 13:28 UTC, RYOTA-EAST commented on app/models/post.rb
> +
userとpostを連携させて論理削除で
doc読んで以下の2通り試しましたがうまく動作しません
[現状の作業状態コミット](https://github.com/masakichi-eng/NekoPro-Tsubuyaki/pull/20/commits/ebefae2de85d6ee55b3e58b63fc52c34aefd4ff1)

①models/post.rbを以下に書き換えて
```
class Post < ApplicationRecord
  include Discard::Model
  scope :kept, -> { undiscarded.joins(:user).merge(User.kept) }

  def kept?
    undiscarded? && user.kept?
  end
```
User.find(1).destroyでユーザーを実際に削除すると連携してpostも削除されます
dependent: :destroyが働いている

②userに論理削除できる様にして
```
  include Discard::Model
  has_many :posts, dependent: :destroy

  after_discard do
    puts posts
    posts.discard_all
  end

  after_undiscard do
    posts.undiscard_all
  end
```
userはUser.find(1).discardで論理削除できますが、postが連なって論理削除されません

2021-08-08 13:40 UTC, minty1202 commented on app/models/post.rb
> +
userの理論削除はハードル高すぎると思うので、実装しなくて良いですよ
連なって理論削除されない理由に関しては現状の質問だけだと、わからないので調べてみますしか言えないですね。

2021-08-08 14:54 UTC, minty1202 commented on app/models/post.rb
> +
userの理論削除は消しておいてもらえると、指示してなくてすみません

userモデルを以下に変更
```
class User < ApplicationRecord
  include Discard::Model
  before_destroy :posts_discard
  has_many :posts, dependent: :nullify

  def posts_discard
    posts.discard_all
  end
end
```
これで動くと思います。

2021-08-08 16:10 UTC, RYOTA-EAST commented on app/models/post.rb
> +
書いていただいたコードで
userが削除された際にpostが削除されない
before_destroyでpostに論理削除かけているとやりたいことを達成していると思うので

models/post.rbのコメント部分は不要（削除）で問題ないでしょうか？
この部分がなければ動作します
```
class Post < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }
  # scope :kept, -> { undiscarded.joins(:user).merge(User.kept) }

  # def kept?
  #   undiscarded? && user.kept?
  # end
```

コメント部分がある場合
`ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column users.discarded_at does not exist)`
userのdiscardedがないとエラーを出してuserの削除からできません

2021-08-08 16:15 UTC, minty1202 commented on app/models/post.rb
> +
まぁぶっちゃけどっちでも良いですが、私の環境では書いてあっても動きましたよ？

2021-08-08 16:29 UTC, minty1202 commented on app/models/post.rb
> +
よくよく思うと最初の参考コード見当違いのものでしたね。失礼しました

2021-08-08 16:34 UTC, RYOTA-EAST commented on app/models/post.rb
> +
了解しました、削除します

2021-08-11 12:09 UTC, RYOTA-EAST commented
昨日はありがとうございました。
一通り修正が完了したと思いますので確認お願いします

- discardのバージョン指定
- userテーブル修正
- modelにコメント追加
- user削除でのpostの論理削除
- requestテスト追加

2021-08-13 11:29 UTC, minty1202 approved these changes

2021-08-13 11:29 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +    end
慣れてきたと思うのでちょっとした小技の紹介です。
変えなくて大丈夫です。
```ruby
render :show and return unless @post.discard

redirect_to root_path, notice: '記事が削除されました'
```
こうやって早期returnを使うことでスッキリ書くこともできます

2021-08-13 11:29 UTC, minty1202 commented on spec/requests/users/posts_spec.rb
> +      expect(Post.with_discarded.find(@post.id).discarded_at.strftime("%Y-%m-%d %H:%M:%S")).to eq(Time.now.strftime("%Y-%m-%d %H:%M:%S"))
```
.strftime("%Y-%m-%d %H:%M:%S")
```
って使わなくてもいい気が。。。

```ruby
expect(Post.with_discarded.find(@post.id).discarded_at.to_s).to eq(Time.current.to_s)
```
でいい気はする。
まぁどちらでもいいですが。

2021-08-13 11:29 UTC, merged