Feature/index
masakichi-eng/NekoPro-Tsubuyaki pull request #22
Opened 2021-08-30 03:08 UTC by RYOTA-EAST

# Why

- 他の人の記事も確認
- 複数記事を確認しやすいようにする

# What

- 投稿記事一覧機能実装
- Gem 'kaminari'によるページネーション実装

## View
[Gyazo link](https://gyazo.com/887fa77bf25ce8ba9ad705c89828df4c)

2021-08-30 12:23 UTC, minty1202 requested changes

2021-08-30 12:23 UTC, minty1202 commented on app/controllers/general_controller.rb
> +    @posts = Post.includes(:user).page(params[:page])
Post.includes(:user).page(params[:page]).per(一ページに表示する量).order(created_at: :desc)

2021-08-30 14:23 UTC, RYOTA-EAST commented on app/controllers/general_controller.rb
> +    @posts = Post.includes(:user).page(params[:page])
1. .per(一ページに表示する量)
config/initializers/kaminari_config.rbの
`config.default_per_page = 2`で設定

1.  .order(created_at: :desc)
マイページと同じくビューに記述

それぞれ分解して記述した方がいいかと思いましたが
周りくどいとも思ったので修正しました、ありがとうございます！

2021-08-30 14:24 UTC, RYOTA-EAST commented
修正完了しましたので再度確認お願いします。

2021-08-31 12:52 UTC, minty1202 commented on app/controllers/general_controller.rb
> +    @posts = Post.includes(:user).page(params[:page])
特別な理由がないかぎりコントローラで定義したものを後からorderで調整するのは基本的に避けるべきです。
viewはあくまで表示させるだけなので、
前回は確かview書いた気もするけど。今回のケースですとコントローラーで定義した方がいいですね。
可読性を上げるならば

```ruby
post_data = Post.includes(:user).order(created_at: :desc) # 収集の記述
@posts = post_data.page(params[:page]) # ページネーションの記述
```

initializersで定義するのもいいですが、どのページでも必ず同じページネーションの数でない限りは書いた方が親切ですね。

2021-08-31 12:53 UTC, merged