Feature/like
masakichi-eng/NekoPro-Tsubuyaki pull request #23
Opened 2021-09-04 06:00 UTC by RYOTA-EAST

# Why
良い記事に反応する
# What
いいね機能実装
# view
[Gayso link](https://gyazo.com/bbe8370fc9b72a1ab92a3f76cc635e3e)

2021-09-04 06:15 UTC, minty1202 requested changes
これだけあっさりできると思ってませんでした

2021-09-04 06:15 UTC, minty1202 commented on app/javascript/packs/application.js
> +var jQuery = require('jquery')
const

2021-09-04 06:15 UTC, minty1202 commented on app/helpers/likes_helper.rb
> +end
使う予定がある？

2021-09-04 06:15 UTC, minty1202 commented on app/controllers/users/likes_controller.rb
> +    @post = Post.find_by(id: params[:post_id])
@post = Post.find(params[:post_id])

2021-09-04 06:15 UTC, minty1202 commented on spec/models/like_spec.rb
> +    end
せっかくなのでRspecらしい書き方にしましょうか、終盤ですし
```ruby
      let(:user) { User.create(name: 'test') }
      let(:pos) { FactoryBot.create(:post) }
      let(:like) { FactoryBot.build(:like, user: @user, post: @post) }
```

2021-09-04 06:15 UTC, minty1202 commented on spec/models/like_spec.rb
> +        expect(@like).to be_valid
```ruby
expect(like).to be_valid
```

2021-09-04 06:15 UTC, minty1202 commented on spec/requests/likes_spec.rb
> +      post users_post_likes_path(user_id: @user.id, post_id: @post.id), xhr: true
beforeかlet で先に定義したほうが早かったのでは？

2021-09-04 06:20 UTC, RYOTA-EAST commented on app/helpers/likes_helper.rb
> +end
ないので削除しました

2021-09-04 08:05 UTC, RYOTA-EAST commented on spec/requests/likes_spec.rb
> +      post users_post_likes_path(user_id: @user.id, post_id: @post.id), xhr: true
`post users_post_likes_path(@like.post_id), xhr: true`に修正しました。

2021-09-04 08:44 UTC, minty1202 commented on spec/requests/likes_spec.rb
> +      post users_post_likes_path(like.post_id), xhr: true
let (:post_likes) { users_post_likes_path(like.post_id), xhr: true }

2021-09-04 08:44 UTC, minty1202 commented on app/views/users/likes/_like.html.slim
> += post.likes.count
```ruby
- pust = User.find(1).likes.find_by(post_id: post.id)
  = link_to users_post_likes_path(post.id),"#{post ? (method: :delete) : (method: :post)}", remote: true
    i.fas.fa-heart.text-danger.ml-3
```

こういう書き方できなかったでしたっけ？
ちょっと記憶が曖昧ですが、できなかったら前のままで

2021-09-04 08:48 UTC, minty1202 commented on app/views/users/likes/_like.html.slim
> += post.likes.count
したのやつも微妙に違うのか。
これだと動いたとしても表記が変わらないのでなしで

2021-09-04 09:06 UTC, RYOTA-EAST commented
requestテストの方もletに修正しようとしますがエラーが発生して動作しません
[Gyazo link](https://gyazo.com/1958072e77838139595ae63c3dad92f9)

値の渡し方のエラーというのは分かるのですがどこの値かわからず止まっています
使い方が間違っているところがあるのでしょうか？
確認お願いします
[その際のコード](https://github.com/masakichi-eng/NekoPro-Tsubuyaki/pull/23/commits/b25e06ce3597c0a69e374349aa9fe21271725f28)

2021-09-04 09:14 UTC, RYOTA-EAST commented on spec/requests/likes_spec.rb
> +      post users_post_likes_path(like.post_id), xhr: true
こういう修正であっているでしょうか？
,の位置に対してエラーが出ます
[Gyazo link](https://gyazo.com/08ab601ea5887cfbd851301b4cd35da2)

2021-09-04 15:16 UTC, RYOTA-EAST commented on spec/requests/likes_spec.rb
> +      post users_post_likes_path(like.post_id), xhr: true
勘違いしてました、letは前段に置くってことですね
「, xhr: true」を入れると先程と同じエラーが出るので
`let(:post_likes) { users_post_likes_path(like.post_id) }`
として
```
    it 'リクエストが成功すること' do
      post post_likes, xhr: true
      expect(response).to be_truthy
    end
```
で動作しました

2021-09-04 15:36 UTC, RYOTA-EAST commented
`post post_likes, xhr: true`
で先頭に記述しているpostが
投稿に使うpostとletで定義した変数postと一緒でエラーを出していたので
let(:new_post)に修正しました

2021-09-04 15:59 UTC, RYOTA-EAST commented on spec/requests/likes_spec.rb
> +  let!(:like2) { FactoryBot.create(:like, user: user, post: new_post2)}
この部分だけlet!に変更しています
letだとモデル数が変化せずテストが通りません。

letは遅延評価で呼ばれないと実行されないとの理解で
下記のように事前にlike2を使用するとletでもテストが通ります

そもそもテストコードの書き方が変なところとかありますか？
```
    it 'いいね解除が成功してモデルが減ること' do
      like2
      expect do
        delete post_likes2, xhr: true
      end.to change(Like, :count).by(-1)
    end
```

2021-09-05 07:30 UTC, minty1202 approved these changes
テストが通るのであれば、いいのでは？
書き方は理想とは言えないですが、初めてだと思いますし

2021-09-05 07:30 UTC, minty1202 commented on spec/requests/likes_spec.rb
> +  let!(:like2) { FactoryBot.create(:like, user: user, post: new_post2)}
1、2という定義は適当ではないですね。

2021-09-05 07:30 UTC, minty1202 commented on spec/requests/likes_spec.rb
> +      end.to change(Like, :count).by(-1)
```ruby
context '成功するとき' do
  let(:delete_path) { delete users_post_likes_path(like.post_id), xhr: true }
  it { expect { delete_path }.to change(Like, :count).by(-1) }
  it do
  delete_path
  expect(response).to be_truthy
  end
end

2021-09-05 07:30 UTC, minty1202 commented on spec/requests/likes_spec.rb
> +  let!(:like2) { FactoryBot.create(:like, user: user, post: new_post2)}
いまいちお伝えしたいことの意味がわかりませんでした。申し訳ないです。

2021-09-05 07:31 UTC, merged