Feature/comment
masakichi-eng/NekoPro-Tsubuyaki pull request #24
Opened 2021-09-08 22:14 UTC by RYOTA-EAST

# Why
記事に対する意見や質問を共有する
# What
コメント機能

# view
[Gayzo link](https://gyazo.com/322c9c2540a76f32500d2fa834dddb26)

2021-09-11 05:54 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    render :index
redirect_back

2021-09-11 05:54 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    render :index
redirect_back

2021-09-11 05:54 UTC, minty1202 commented on app/views/users/comments/index.js.erb
> +$("#comment-text-<%= @post.id %>").val('')
このページ存在するのでしょうか？

2021-09-11 05:54 UTC, minty1202 commented on app/controllers/general_controller.rb
> +    @comment = Comment.new
これの必要性があまりわからなかったです

2021-09-11 05:54 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +    @comment = Comment.where(post_id: params[:post_id])
複数形

2021-09-11 05:54 UTC, minty1202 commented on app/views/general/index.html.slim
> +            = render partial: 'users/comments/form', locals: { post: post }
renderでなくていいです

2021-09-11 06:50 UTC, RYOTA-EAST commented on app/controllers/general_controller.rb
> +    @comment = Comment.new
省略してみました
[コミット内容](https://github.com/masakichi-eng/NekoPro-Tsubuyaki/pull/24/commits/ae8fdc5eb092b30144de27a22765c1293e33b9d3)

2021-09-11 06:50 UTC, RYOTA-EAST commented on app/views/general/index.html.slim
> +            = render partial: 'users/comments/form', locals: { post: post }
general/indexとpost/showでコメントを
動かすのに部分テンプレートをrenderで呼び出していますが
直接記述でいいという感じですか？

2021-09-11 06:51 UTC, RYOTA-EAST commented on app/views/users/comments/index.js.erb
> +$("#comment-text-<%= @post.id %>").val('')
app/views/users/comments/_index.html.slim
の部分テンプレートをrenderで読み出しているので
動作していると思っていますがどうでしょうか？

2021-09-11 07:04 UTC, RYOTA-EAST commented on app/controllers/users/comments_controller.rb
> +    render :index
render :indexでapp/views/users/comments/index.js.erbを
読み出してコメントを更新しているのが動作しなくなります。

2021-09-11 07:25 UTC, RYOTA-EAST commented
一通り確認と修正しました。
質問もあるので回答お願いします

2021-09-11 08:18 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    render :index
前提として、render :indexのみの記述ですとCommentsControllerを呼び出すという意味なのでこの動き自体が期待通りにうごくのがおかしいです。
rails側で表示されているpostを自動で参照してくれているだけで書き方として綺麗ではありません。

2021-09-11 08:21 UTC, minty1202 commented on app/views/users/comments/index.js.erb
> +$("#comment-text-<%= @post.id %>").val('')
commentsにindexが存在しないのでこのページがあるのは違和感です。
renderで一覧を呼び出したいのであれば、postディレクトリに _comment_indexとしてあるべきですね。

2021-09-11 08:23 UTC, minty1202 commented on app/views/general/index.html.slim
> +            = render partial: 'users/comments/form', locals: { post: post }
直接記述で問題ないです。
ajaxにするにしても色々と噛み合っていないので、素直に直接記述redairectした方が綺麗だと思います

2021-09-11 08:24 UTC, minty1202 commented
回答いたしました。
結論としては直接記述に変更して、redirect_backを使った方がいいかと

2021-09-12 12:16 UTC, RYOTA-EAST commented
修正しました、確認お願いします

2021-09-13 11:02 UTC, minty1202 requested changes

2021-09-13 11:02 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    Comment.create(user_id: 1, post_id: @post.id, comment: params[:comment][:comment])
@post.comments.create(......)
params[:comment][:comment]がすごく違和感です。

2021-09-13 11:02 UTC, minty1202 commented on app/controllers/users/posts_controller.rb
> +    @comments = Comment.where(post_id: params[:post_id])
前回気づけばよかったのですが、この記述不要だと思います
@post.commentsで取得できるかと

2021-09-13 11:02 UTC, minty1202 commented on app/views/general/index.html.slim
> +            = form_with model: [post, post.comments], url: users_post_comments_path(post) do |f|
urlを指定していてmodel: [post, post.comments]この書き方をするわざわざする必要はないかと

2021-09-13 11:02 UTC, minty1202 commented on app/views/users/posts/show.html.slim
> +            .comment-area-show.text-left.ml-3.overflow-auto id = "comments-#{@post.id}"
idを指定する理由を教えていただけると助かります。
直して欲しいのではなく、
classでもいいのではと思ったのでご意見を聞きたいです

2021-09-13 11:02 UTC, minty1202 commented on app/views/users/posts/show.html.slim
> +            = form_with model: [@post, @comments], url: users_post_comments_path(@post) do |f|
同上

2021-09-13 11:02 UTC, minty1202 commented on spec/requests/comments_spec.rb
> +        post path_build_comment, params: { comment: {comment: build_comment }}, xhr: true
ajaxでは無くなったと思ったのですが、違うのでしょうか？

2021-09-13 11:02 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    Comment.create(user_id: 1, post_id: @post.id, comment: params[:comment][:comment])
あーparams[:comment][:comment]の理由がわかったのでそのままでいいです

2021-09-13 14:59 UTC, RYOTA-EAST commented on app/views/users/posts/show.html.slim
> +            .comment-area-show.text-left.ml-3.overflow-auto id = "comments-#{@post.id}"
idはそのページに一つだけとhtmlのルールがあると知ってから
javascriptで要素指定を使うときはidを設定して対象にする
という好みの書き方になります

classでもいいです、と言うよりajaxでなくなったので不要ですかね？

2021-09-13 15:22 UTC, RYOTA-EAST commented on spec/requests/comments_spec.rb
> +        post path_build_comment, params: { comment: {comment: build_comment }}, xhr: true
おっしゃる通りです、
`xhr: true`
を削除しました

2021-09-13 15:26 UTC, RYOTA-EAST commented on app/controllers/users/posts_controller.rb
> +    @comments = Comment.where(post_id: params[:post_id])
確かに不要でしたので削除しました

2021-09-13 15:36 UTC, RYOTA-EAST commented
修正完了しました
idの件はコメントのあった部分以外に
form_with内のtext_fieldでも指定しています

2021-09-14 00:48 UTC, minty1202 commented on app/views/users/posts/show.html.slim
> +            .comment-area-show.text-left.ml-3.overflow-auto id = "comments-#{@post.id}"
なるほど、理解しました。
今回はajax出なくなったので消していただけると

2021-09-14 12:30 UTC, RYOTA-EAST commented
ajaxで使用していたidを削除しました

2021-09-14 13:00 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    Comment.create(user_id: 1, post_id: @post.id, comment: params[:comment])
@post.comments.create(...

2021-09-14 22:07 UTC, RYOTA-EAST commented on app/controllers/users/comments_controller.rb
> +    Comment.create(user_id: 1, post_id: @post.id, comment: params[:comment])
Comment.createの様にモデルに直接createする記述は好ましくないという感じでしょうか？

2021-09-16 03:09 UTC, minty1202 requested changes

2021-09-16 03:09 UTC, minty1202 commented on app/controllers/users/comments_controller.rb
> +    @post.comments.create(user_id: 1, post_id: @post.id, comment: params[:comment])
post_id: @post.id
は不要です

2021-09-16 03:09 UTC, minty1202 commented on app/views/general/index.html.slim
> +            = form_with url: users_post_comments_path(post), local: true do |f|
```ruby
= form_with model comment, url: users_post_comments_path(post), local: true do |f|
```

modelはrailsが判断して行ってくれますが、明示的に何に対して送りたいのかは書いてくださった方がいいです。
おそらくこれに伴ってparamsの中身も少し変わる可能性があります。
model [..., ...]
という書き方でなくていいですよという意味です。紛らわしくてすみません。
newを定義していなくてエラーになる場合は修正しなくて大丈夫です

2021-09-16 03:09 UTC, minty1202 commented on app/views/general/index.html.slim
> +              - post.comments.each do |comment|
別件ですが、
N+1が発生していないでしょうか？

2021-09-17 01:42 UTC, RYOTA-EAST commented on app/controllers/users/comments_controller.rb
> +    @post.comments.create(user_id: 1, post_id: @post.id, comment: params[:comment])
確かに不要ですね、削除しました。

2021-09-17 01:57 UTC, RYOTA-EAST commented on app/views/general/index.html.slim
> +            = form_with url: users_post_comments_path(post), local: true do |f|
newを定義しないとエラーが出るのでこのままでいきます

formで対象のmodelを指定した方がいいということですね
ここら辺を修正したときにparams[:comment][:comment]とかの
理解が深まった気がします、ありがとうございました

2021-09-17 02:04 UTC, RYOTA-EAST commented on app/views/general/index.html.slim
> +              - post.comments.each do |comment|
@post > comments > user で参照しているところでN+1問題が発生していましたので解消しました
## general/index表示時ターミナル画像
（1つ目の記事コメント4件、2つ目は3件）
[解消前](https://gyazo.com/649b239ef80aa51ba4b3bb5fcf284793)
[解消後](https://gyazo.com/511ae0b7d185ef290398be94ce827c14)

## commit
[N+1解消](https://github.com/masakichi-eng/NekoPro-Tsubuyaki/pull/24/commits/6a017d886783f9ab818da58c2e36ba275b9b7517)

2021-09-17 05:33 UTC, minty1202 approved these changes

2021-09-17 05:33 UTC, minty1202 commented on app/views/general/index.html.slim
> +              - post.comments.each do |comment|
ありがとうございます〜
ここら辺の判断は慣れの部分が大きいので最初のうちは複数のモデルを跨ぐときはログを見るのが無難ですね。

2021-09-17 05:33 UTC, minty1202 commented on app/views/general/index.html.slim
> +            = form_with url: users_post_comments_path(post), local: true do |f|
よかったです。

2021-09-17 05:33 UTC, merged